//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SIKP
//  @ File Name : LaporanKemajuanKP.cs
//  @ Date : 12/28/2014
//  @ Author : 
//
//


public class LaporanKemajuanKP : KerjaPraktik {
    public int idLaporan { get; set; }
	public int idKelompok { get; set; }
	private string tanggalLaporan { get; set; }
	private string fileLaporanMingguan { get; set; }
	private bool statusKeterlambatanLaporan { get; set; }
}
