//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SIKP
//  @ File Name : Mahasiswa.cs
//  @ Date : 12/28/2014
//  @ Author : 
//
//


public class Mahasiswa : KerjaPraktik {
    public string nrpMahasiswa { get; set; }
    public int idKelompok { get; set; }
    private string namaMahasiswa { get; set; }
    private int sksTempuh { get; set; }
    private string passwordMahasiswa { get; set; } 
}
