//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SIKP
//  @ File Name : NilaiHasilKerjaPraktik.cs
//  @ Date : 12/28/2014
//  @ Author : 
//
//


public class NilaiHasilKerjaPraktik : KerjaPraktik{
    public int kodeKegiatan { get; set; }
    public string NRP { get; set; }
    private string namaKegiatan { get; set; }
    private int nilaiKegiatanPembimbing { get; set; }
    private int nilaiKegiatanDosbing { get; set; }
    private int nilaiKegiatanTotal { get; set; }
    private string notePembimbing { get; set; }
    private string noteDosbing { get; set; } 
}
