//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SIKP
//  @ File Name : Pegawai.cs
//  @ Date : 12/28/2014
//  @ Author : 
//
//


public class Pegawai : KerjaPraktik{
    public string NIP { get; set; }
    private string namaPegawai { get; set; }
    private string jabatan { get; set; }
    private string passwordMahasiswa { get; set; } 
}
