//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SIKP
//  @ File Name : Perusahaan.cs
//  @ Date : 12/28/2014
//  @ Author : 
//
//


public class Perusahaan : KerjaPraktik{
    public int kodePerusahaan { get; set; }
    private string namaPerusahaan { get; set; }
    private string alamatPerusahaan { get; set; }
    private string telpPerusahaan { get; set; } 
}
